name: Build, Test and Create New Version

on:
  push:
    branches:
      - master

jobs:
  build-test:
    if: github.actor != 'github-actions[bot]'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2

      - id: set-up-jdk
        name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - id: mvn-verify
        if: success()
        name: Check if build is successful
        run: mvn verify

      - id: mvn-clean-install
        if: success()
        name: Build with Maven
        run: mvn clean install

  increase-version:
    needs:
      - build-test
    if: success() && github.actor != 'github-actions[bot]'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2

      - id: set-up-jdk
        name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase needed for signing

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          # Install gpg secret key
          echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG

      - id: increment-version
        name: Determine Version and Increments it
        if: success()
        run: |
          # get the last commit message
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: '$commit_message'"
          
          # Check if the commit message starts with the specified word
          if [[ $commit_message == "feat: "* ]]; then
            mvn build-helper:parse-version \
            versions:set \
            -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0 \
            versions:commit
          elif [[ $commit_message == "fix: "* ]]; then
            mvn build-helper:parse-version \
            versions:set \
            -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} \
            versions:commit
          else
            echo "Commit message does not start with either 'feat:' or 'fix:'"
            exit 1
          fi

      - id: set-up-git-user
        if: success()
        name: Set up Git user
        run: |
          git config --global user.name "H@JJ"
          git config --global user.email "hajj@hajj.mozmail.com"

      - id: push-changes
        if: success()
        name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        run: |
          git config --global user.signingkey ${{ secrets.OSSRH_GPG_KEY }}
          git commit -S -am "Release ${VERSION}"
          git push origin HEAD:master

      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      - id: create-release-tag
        if: success()
        name: Create Release Tag
        run: |
          git tag -a \
          v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) \
          -m "Release $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
