name: Pull Request Check Labels

on:
  pull_request:
    branches:
      - master

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2

      - id: set-up-jdk
        name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - id: mvn-verify
        if: success()
        name: Check if build is successful
        run: mvn verify

      - id: mvn-clean-install
        if: success()
        name: Build with Maven
        run: mvn clean install