name: Publish package to the Maven Central Repository
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          settings-path: ${{ github.workspace }}
          server-id: ossrh
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Verify package
        run: mvn clean verify

      - name: Publish package
        run: mvn clean deploy -P release -DskipTests

      - name: Commit and push release
        run: |
          git add pom.xml target/*.jar
          git commit -m "Release ${VERSION}"
          git push